---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    service: service-a
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: service-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  labels:
    account: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-v1
  labels:
    app: service-a
    version: v1
spec:
  selector:
    matchLabels:
      app: service-a
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
        version: v1
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a-v1
        image: anevigat/python-rest:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        env:
          - name: APP_NAME
            value: "service-a"
          - name: VERSION
            value: "v1"
          - name: CONNECT_URL
            value: "http://service-b:5000/"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP