---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
    service: service-b
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: service-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  labels:
    account: service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-v2
  labels:
    app: service-b
    version: v2
spec:
  selector:
    matchLabels:
      app: service-b
      version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: service-b
        version: v2
    spec:
      serviceAccountName: service-b
      containers:
      - name: service-b-v2
        image: anevigat/python-rest:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        env:
          - name: APP_NAME
            value: "service-b-v2"
          - name: VERSION
            value: "v2"
          - name: CONNECT_URL
            value: "https://www.google.es"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP